DROP TABLE IF EXISTS PRICES;

CREATE TABLE PRICES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID INT,
    START_DATE CHAR(19) NOT NULL,
    END_DATE CHAR(19) NOT NULL,
    PRICE_LIST INT NOT NULL,
    PRODUCT_ID VARCHAR(10) DEFAULT NULL,
    PRIORITY INT,
    PRICE FLOAT,
    CURR CHAR(3)
);